spring:
  application:
    name: chat_be
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/chat_db # 예시로 localhost에 MariaDB가 설치되어 있다고 가정
    username: root
    password: '!123456'
  sql:
    init:
      mode: never
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true
